config:
  target: http://localhost:3005
  phases:
    - duration: 60
      arrivalRate: 10
      name: "Warm up"
    - duration: 120
      arrivalRate: 50
      name: "Ramp up load"
    - duration: 180
      arrivalRate: 100
      name: "Sustained load"
    - duration: 60
      arrivalRate: 200
      name: "Peak load"
scenarios:
  - name: "Health Check Load"
    weight: 30
    flow:
      - get:
          url: "/health"
  - name: "API Endpoints Load"
    weight: 70
    flow:
      - get:
          url: "/api/deployments"
      - get:
          url: "/health/database"
      - get:
          url: "/health/services"